# Generated by Django 2.2.28 on 2023-05-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demofields',
            name='witch_hunt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
