# Generated by Django 2.2.28 on 2023-05-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
