# Generated by Django 2.2.28 on 2023-05-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_partytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt', models.BigIntegerField()),
            ],
        ),
    ]
