# Generated by Django 2.2.28 on 2023-05-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tt'),
    ]

    operations = [
        migrations.AddField(
            model_name='partytime',
            name='asdfasdfasdf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
