# Generated by Django 2.2.28 on 2023-06-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_partytime_asdfasdfasdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ttttttt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddddd', models.BigIntegerField()),
            ],
        ),
    ]
